### ISSUE TITLE
A question about ground truth distance

### ISSUE THREAD

**Issue by alex-wy** [tum-pbs/LSIM#1]
Hello, I've read ur paper about LSIM carefully. Very excellent work!

But I got a question about how to **compute the ground truth distance**.
I found that the paper said:
> "distortions, noise, or other operations and assigning ground truth distances according to **the strength of the operation**"

However, I cannot find **the specific method to compute the value of ground truth by parameter increments or injected noise**.
Could u please tell me the way u use to caculate the ground truth distance? 

Besides, I'm also wanna know how to judge **the level of similarity** in different domain by the LSIM metric output value.
I think the same value of ouput cannot represent the two inputs have the **same similarity** if the inputs come from **different domain**(e.g. density, velocity, level set, etc.). Am I right? 

Hope u can answer my questions. THX!

**Comment by GeorgKohl** [comment]
Hello, thanks for your questions and your interest in our work.

It is not necessary to explicitly compute the ground truth distances in our case. Instead they can be directly inferred from the order and number of the input simulations and are more or less fixed for all data.
There are two reasons why it works in this way: First, since the parameter/noise is always changed linearly with a fixed step size (denoted as ∆_i in Fig. 3 in the paper), we know that the distances should be spaced evenly. Second, since we always use one reference and ten variation simulations for training, having the most dissimilar variation at a normalized distance of 1.0 always leads to the same steps in the ground truth distances. If the amount of variations would be different, a different spacing size would be required as well.

**Example:** Lets assume we have a smoke simulation with a smoke source at a position p and create variations of it by adjusting p in steps of two pixels. Obviously, we would get simulations with the source at p, p+2, p+4, ... , p+20 (up to 20 since we always create 10 variants per reference). Next, we need normalized ground distances in [0,1] of these simulations for training, and the distances should be spaced evenly like the relative simulation parameter changes. So we would take the range of parameter change and map it to [0,1] for the ground truth distances. As a result we would get distances of 0, 0.1, 0.2, ... ,1.0 from each simulation to the reference. For other pairs, like p+2 <-> p+6, we can just take the difference between the distances to the reference which would give us 0.2 here.
Similarly, if we e.g. have a simulation with noise strength of n and then increase the noise level ten times in steps of 0.02, it works in exactly the same way. We would still end up at the same ground truth distances of  0, 0.1, 0.2, ... ,1.0 from each simulation to the reference, due to the normalization to [0,1].

For your second question, yes it is correct that LSiM does not make different data domains comparable. Making statements about the similarity of data with different meaning (e.g. a pressure and a velocity field) is inherently not really useful. The same goes for comparing different simulation types between each other (e.g. a liquid and a smoke simulation). During training we don't have any pairs containing different data, but only compare data that semantically makes sense (i.e. one field of a reference simulation vs. the same field of a variation simulation with a parameter change). In theory, it is possible to give the network any two data samples during inference, but the resulting distances mostly likely won't be really meaningful. In a way, the metric is only trained for simulation pairs that already have a certain semantic similarity, where a finer judgement than "_these two data points are not similar at all_" is required.

I hope this answers your questions.

**Comment by alex-wy** [comment]
> Hello, thanks for your questions and your interest in our work.
> 
> It is not necessary to explicitly compute the ground truth distances in our case. Instead they can be directly inferred from the order and number of the input simulations and are more or less fixed for all data.
> There are two reasons why it works in this way: First, since the parameter/noise is always changed linearly with a fixed step size (denoted as ∆_i in Fig. 3 in the paper), we know that the distances should be spaced evenly. Second, since we always use one reference and ten variation simulations for training, having the most dissimilar variation at a normalized distance of 1.0 always leads to the same steps in the ground truth distances. If the amount of variations would be different, a different spacing size would be required as well.
> 
> **Example:** Lets assume we have a smoke simulation with a smoke source at a position p and create variations of it by adjusting p in steps of two pixels. Obviously, we would get simulations with the source at p, p+2, p+4, ... , p+20 (up to 20 since we always create 10 variants per reference). Next, we need normalized ground distances in [0,1] of these simulations for training, and the distances should be spaced evenly like the relative simulation parameter changes. So we would take the range of parameter change and map it to [0,1] for the ground truth distances. As a result we would get distances of 0, 0.1, 0.2, ... ,1.0 from each simulation to the reference. For other pairs, like p+2 <-> p+6, we can just take the difference between the distances to the reference which would give us 0.2 here.
> Similarly, if we e.g. have a simulation with noise strength of n and then increase the noise level ten times in steps of 0.02, it works in exactly the same way. We would still end up at the same ground truth distances of 0, 0.1, 0.2, ... ,1.0 from each simulation to the reference, due to the normalization to [0,1].
> 
> For your second question, yes it is correct that LSiM does not make different data domains comparable. Making statements about the similarity of data with different meaning (e.g. a pressure and a velocity field) is inherently not really useful. The same goes for comparing different simulation types between each other (e.g. a liquid and a smoke simulation). During training we don't have any pairs containing different data, but only compare data that semantically makes sense (i.e. one field of a reference simulation vs. the same field of a variation simulation with a parameter change). In theory, it is possible to give the network any two data samples during inference, but the resulting distances mostly likely won't be really meaningful. In a way, the metric is only trained for simulation pairs that already have a certain semantic similarity, where a finer judgement than "_these two data points are not similar at all_" is required.
> 
> I hope this answers your questions.

Thank u so much for responding so quickly and carefully! It helps me a lot for understaning ur work!

Sorry I still have some doubts.

For ur 1st **Example**: How can I compute distance if I **changed multiple properties** at the same time?
E.g. What is the ground truth between p+2 at the timesteps of 0.04(noise level) and p+6 at the timestep of 0.02(noise level)? I think it cannot just add them together cuz the variants of different property cannot be equivalent.

For the 2nd one, I got a further question. If I got the same ouput distance between **2 pairs in different fields**, it's meaningless to compare the which pair is more similar cuz they're **in the different field and  both normalized**. Right?
E.g. I input 2 density samples and 2 velocity samples seperately and get the ouput distance of 0.2 and 0.3. It cannot say the former density pair is more similar than the latter velocity pair.

Thx for ur patience and kindness.

**Comment by GeorgKohl** [comment]
Regarding the example: We do not consider case of multiple change parameters at the same time. So either the source position would be changed with a constant noise level, or the noise level would be varied while keeping the source position constant. The main reason why we are not doing this, is that there can be complicated interdependencies between both parameters. That means coming up with a meaningful ground truth distance might get tricky or not directly possible at all anymore. The simplest case would be to imagine if you change the smoke source position in x-direction while also moving a downwards directed force field that splits the smoke stream by the same amount in the same direction. In this case, any ground truth distances don't really make sense anymore and are basically just random, since the simulation would be essentially the same (ignoring boundary effects, spatially fixed seeded noise, numerical errors, etc. for simplicity here).
One example where two changes at once might not be that problematic, is a translation of the smoke source in x- and y-direction at the same time. This would in some way correspond to a single, diagonal parameter change that might still work as expected. Your example of varied noise + varied position is probably somewhere in the middle between those cases, so it's hard to tell if it would work or not. An inaccurate heuristic could be to try it and look at the resulting data. If a human can't recongize any trend whatsoever with increasingly different parameters, a network might not be able to either.

Regarding your question of two pairs of fields: I'm not sure if I fully understand your question here. I guess it depends on what you mean by more similar in this case, since we are not talking about the similarity of simulations any more, but about the similarity of the resulting distances instead. In a strict mathematical sense, the distance of 0.2 is obviously smaller than 0.3 so the two density samples are "closer together" in the distance output space compared to the two velocity samples. But I don't think this information is of any real value, since normally a shared reference point is required. When you look at the distances as a single number, the physical meaning is lost. If you think about a simple mean absolute difference instead, a density difference would still carry a unit of density while a velocity difference would still carry a velocity unit. So I would say in general you are right, and that is not a meaningful comparison.

**Comment by alex-wy** [comment]
> Regarding the example: We do not consider case of multiple change parameters at the same time. So either the source position would be changed with a constant noise level, or the noise level would be varied while keeping the source position constant. The main reason why we are not doing this, is that there can be complicated interdependencies between both parameters. That means coming up with a meaningful ground truth distance might get tricky or not directly possible at all anymore. The simplest case would be to imagine if you change the smoke source position in x-direction while also moving a downwards directed force field that splits the smoke stream by the same amount in the same direction. In this case, any ground truth distances don't really make sense anymore and are basically just random, since the simulation would be essentially the same (ignoring boundary effects, spatially fixed seeded noise, numerical errors, etc. for simplicity here).
> One example where two changes at once might not be that problematic, is a translation of the smoke source in x- and y-direction at the same time. This would in some way correspond to a single, diagonal parameter change that might still work as expected. Your example of varied noise + varied position is probably somewhere in the middle between those cases, so it's hard to tell if it would work or not. An inaccurate heuristic could be to try it and look at the resulting data. If a human can't recongize any trend whatsoever with increasingly different parameters, a network might not be able to either.
> 
> Regarding your question of two pairs of fields: I'm not sure if I fully understand your question here. I guess it depends on what you mean by more similar in this case, since we are not talking about the similarity of simulations any more, but about the similarity of the resulting distances instead. In a strict mathematical sense, the distance of 0.2 is obviously smaller than 0.3 so the two density samples are "closer together" in the distance output space compared to the two velocity samples. But I don't think this information is of any real value, since normally a shared reference point is required. When you look at the distances as a single number, the physical meaning is lost. If you think about a simple mean absolute difference instead, a density difference would still carry a unit of density while a velocity difference would still carry a velocity unit. So I would say in general you are right, and that is not a meaningful comparison.

Very clear answer and totally solved my question.

Thank u again for ur help!
